const default_tasks = [
    {
        id: 1,
        name: 'Тестовая задача №1',
        created: 'только что',
        priority: 'normal',
        marks: ['design', 'development'],
        description: '',
    },
    {
        id: 2,
        name: 'Тестовая задача №2',
        created: '5 минут назад',
        priority: 'high',
        marks: ['design'],
        description: '',
    },
    {
        id: 3,
        name: 'Тестовая задача №3',
        created: '9 часов назад',
        priority: 'high',
        marks: ['research'],
        description: '',
    },
    {
        id: 4,
        name: 'Тестовая задача №4',
        created: '20 октября 2020, 16:25',
        priority: 'normal',
        marks: ['design', 'development', 'research'],
        description: '',
    },
    {
        id: 5,
        name: 'Тестовая задача №5',
        created: 'только что',
        priority: 'normal',
        marks: ['design', 'development'],
        description: '',
    },
    {
        id: 6,
        name: 'Тестовая задача №6',
        created: '5 минут назад',
        priority: 'high',
        marks: ['design'],
        description: '',
    },
    {
        id: 7,
        name: 'Тестовая задача №7',
        created: '9 часов назад',
        priority: 'high',
        marks: ['research'],
        description: '',
    },
    {
        id: 8,
        name: 'Тестовая задача №8',
        created: '20 октября 2020, 16:25',
        priority: 'normal',
        marks: ['design', 'development', 'research'],
        description: '',
    },
    {
        id: 9,
        name: 'Тестовая задача №9',
        created: 'только что',
        priority: 'normal',
        marks: ['design', 'development'],
        description: '',
    },
    {
        id: 10,
        name: 'Тестовая задача №10',
        created: '5 минут назад',
        priority: 'high',
        marks: ['design'],
        description: '',
    },
    {
        id: 11,
        name: 'Тестовая задача №11',
        created: '9 часов назад',
        priority: 'high',
        marks: ['research'],
        description: '',
    },
    {
        id: 12,
        name: 'Тестовая задача №12',
        created: '20 октября 2020, 16:25',
        priority: 'normal',
        marks: ['design', 'development', 'research'],
        description: '',
    },
    {
        id: 13,
        name: 'Тестовая задача №13',
        created: 'только что',
        priority: 'normal',
        marks: ['design', 'development'],
        description: '',
    },
    {
        id: 14,
        name: 'Тестовая задача №14',
        created: '5 минут назад',
        priority: 'high',
        marks: ['design'],
        description: '',
    },
    {
        id: 15,
        name: 'Тестовая задача №15',
        created: '9 часов назад',
        priority: 'high',
        marks: ['research'],
        description: '',
    },
    {
        id: 16,
        name: 'Тестовая задача №16',
        created: '20 октября 2020, 16:25',
        priority: 'normal',
        marks: ['design', 'development', 'research'],
        description: '',
    },
    {
        id: 17,
        name: 'Тестовая задача №17',
        created: 'только что',
        priority: 'normal',
        marks: ['design', 'development'],
        description: '',
    },
    {
        id: 18,
        name: 'Тестовая задача №18',
        created: '5 минут назад',
        priority: 'high',
        marks: ['design'],
        description: '',
    },
    {
        id: 19,
        name: 'Тестовая задача №19',
        created: '9 часов назад',
        priority: 'high',
        marks: ['research'],
        description: '',
    },
    {
        id: 20,
        name: 'Тестовая задача №20',
        created: '20 октября 2020, 16:25',
        priority: 'normal',
        marks: ['design', 'development', 'research'],
        description: '',
    },
    {
        id: 21,
        name: 'Тестовая задача №21',
        created: 'только что',
        priority: 'normal',
        marks: ['design', 'development'],
        description: '',
    },
    {
        id: 22,
        name: 'Тестовая задача №22',
        created: '5 минут назад',
        priority: 'high',
        marks: ['design'],
        description: '',
    },
    {
        id: 23,
        name: 'Тестовая задача №23',
        created: '9 часов назад',
        priority: 'high',
        marks: ['research'],
        description: '',
    },
    {
        id: 24,
        name: 'Тестовая задача №24',
        created: '20 октября 2020, 16:25',
        priority: 'normal',
        marks: ['design', 'development', 'research'],
        description: '',
    },
    {
        id: 25,
        name: 'Тестовая задача №25',
        created: 'только что',
        priority: 'normal',
        marks: ['design', 'development'],
        description: '',
    },
    {
        id: 26,
        name: 'Тестовая задача №26',
        created: '5 минут назад',
        priority: 'high',
        marks: ['design'],
        description: '',
    },
    {
        id: 27,
        name: 'Тестовая задача №27',
        created: '9 часов назад',
        priority: 'high',
        marks: ['research'],
        description: '',
    },
    {
        id: 28,
        name: 'Тестовая задача №28',
        created: '20 октября 2020, 16:25',
        priority: 'normal',
        marks: ['design', 'development', 'research'],
        description: '',
    },
    {
        id: 29,
        name: 'Тестовая задача №29',
        created: '5 минут назад',
        priority: 'high',
        marks: ['design'],
        description: '',
    },
    {
        id: 30,
        name: 'Тестовая задача №30',
        created: '9 часов назад',
        priority: 'high',
        marks: ['research'],
        description: '',
    },
]

export default default_tasks;